### ISSUE TITLE
zope.component.getMultiAdapter(name=None) breaks registry

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.component#24]
It seems that calling `zope.component.getMultiAdapter` with `name=None` breaks the component registry somehow. Each subsequent call using `zope.component.getMultiAdapter` leads to `Could not adapt.` even for adapters which were returned beforehand.

Tasks:
- Write a test to verify this behavior.
- analyze and resolve the error

**Comment by icemac** [comment]
Probably fixed by zopefoundation/zope.interface#81

**Comment by tseaver** [comment]
@icemac Correct: that PR now prohibits anything other than text for the `name` argument.
