### ISSUE TITLE
Travis builds are broken

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.component#26]
Apparently due to old configuration. See https://github.com/zopefoundation/zope.component/pull/25#issuecomment-311806760

**Comment by tseaver** [comment]
I think this is the setuptools namespace-on-py35 problem again.

**Comment by jamadden** [comment]
Also the “default pypy3 is 3.2” issue.

**Comment by stevepiercy** [comment]
Perhaps adapting some of Pyramid's [.travis.yml](https://github.com/Pylons/pyramid/blob/master/.travis.yml) would work?

**Comment by jamadden** [comment]
zope.testrunner doesn't depend on zope.component so we should be able to use it here in our usual namespace workaround.
