### ISSUE TITLE
Adapters registered for * (wildcard) do not adapt to base types (str, int etc.)

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.component#4]
In https://bugs.launchpad.net/zope.component/+bug/139690, @malthe reported:

> Register an adapt like so:
> 
> ``` xml
> <adapter
>    for="*"
>    provides="IMyInterface"
>    factory=".test" />
> ```
> 
> ``` python
> def test(obj): pass
> ```
> 
> Observe that `IMyInterface("hello")` results in a `ComponentLookupError`.

@cjw296 followed up:

> I can confirm this.
> 
> I mailed this zope3-dev mailing about this some time ago: http://mail.zope.org/pipermail/zope3-dev/2007-January/021576.html
> 
> I seem to remember the problem is with the underlying adapter machinery and not the zcml...

**Comment by jamadden** [comment]
This seems to no longer be a problem. Given this code:
```python
from zope.configuration import xmlconfig
from zope.interface import Interface

conf_str = """
<configure
    xmlns="http://namespaces.zope.org/zope"
    i18n_domain="zope"
    >
   <include package="zope.component" file="meta.zcml" />
   <adapter for="*"
            provides="__main__.IMyInterface"
            factory="__main__.factory" />
</configure>
"""

class IMyInterface(Interface):
    pass

def factory(thing):
    print(" -> Calling factory with", thing)
    return 42


xmlconfig.string(conf_str)

for obj in "hello", 24, 32.0, (), object():
    print("Adapting", repr(obj), "->", IMyInterface(obj))
```

It runs exactly as expected:
```console
$ python /tmp/test.py
 -> Calling factory with hello
Adapting 'hello' -> 42
 -> Calling factory with 24
Adapting 24 -> 42
 -> Calling factory with 32.0
Adapting 32.0 -> 42
 -> Calling factory with ()
Adapting () -> 42
 -> Calling factory with <object object at 0x1077de310>
Adapting <object object at 0x1077de310> -> 42
```
