### ISSUE TITLE
`zcml`: determine `provides` for `subscriber` if not specified (as for `adapter`)

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/zope.component#40]
`zope.component.zcml.adapter` determines `provides` automatically when it is not specified.

Sometimes, `subscriber` is used to register an adapter (the so called `subscription adapter`s).  It would be natural when it treated `provides` in this case in the same way as `adpater`.

**Comment by jamadden** [comment]
Duplicate of #9.
