### ISSUE TITLE
Adapter doesn't know its own name

### ISSUE THREAD

**Issue by djay** [zopefoundation/zope.component#41]
There are cases where the same adapter code is used for multiple  named adapter registrations. There currently isn't an easy way for that code to know which name was used during adaption so it can modify its own behaviour. This would be very useful in particular when using a local registry to dynamically add adapters.

**Comment by d-maurer** [comment]
Dylan Jay wrote at 2019-8-7 00:30 -0700:
>There are cases where the same adapter code is used for multiple  named adapter registrations. There currently isn't an easy way for that code to know which name was used during adaption so it can modify its own behaviour. This would be very useful in particular when using a local registry to dynamically add adapters.

The main adapter infrastructure is now in `zope.interface[.adapter]`.

An adapter could likely use frame inspection (--> `sys._getframe`)
to find out the name for the registration leading to its activation.

Obviously, additional information (such as the registration name)
could not be stored on the adapter itself (as different names apply
in different situations). Thus, either the adapter
would need to be wrapped (giving the problem how the adapter
accesses its wrapper - the easiest way is likely again via frame
inspection) or the adapter would need to be called with additional
parameters. For the latter, an adapter would need a way
to indicate that it is ready to accept additional parameters.


Given the difficulties, I think that doing the wrapping yourself
could be a good solution -- maybe along the following lines:
  *  implement a custom `adapter` registration
  *  define an interface `INamedAdapter` with method
     `instantiate_with_name`
  *  if the custom `adapter` encounters an adapter factory providing
     `INamedAdapter`, it calls its `instantiate_with_name` with
     the provided name. This likely will copy the factory
     and set the given name in the copy.

**Comment by icemac** [comment]
I think if the behavior of the adapter depends on the name the adapter is registered for, then a different class or function should be registered.
The idea behind the adapter registry is that the adapter code itself does _not_ need if statements to decide what context or name it was called for. So it seems you are asking for support to implement an anti-pattern.

**Comment by djay** [comment]
@icemac There are clearly edge cases where adding extra classes is not possible otherwise I wouldn't have suggested it. One example where I need this is https://github.com/collective/collective.listingviews/blob/master/src/collective/listingviews/browser/views/controlpanel.py#L123 where I'm doing registrations dynamically using the local site manager instead of via ZCML. I don't think I can create classes on the fly here to solve your idea of the correct way to register adapters as the local site manager can't persist such class references I'm pretty sure.

@d-maurer the frame hack is indeed how I solve this at the moment - https://github.com/collective/collective.listingviews/blob/master/src/collective/listingviews/browser/views/base.py#L30
```
def getAdapterName():
    for frame, file, lineno, name, line, _ in inspect.stack():
        # HACK
        if 'zope/interface/adapter.py' in file and name == 'queryMultiAdapter':
            return inspect.getargvalues(frame).locals['name']
```

I'll have a think about your wrapping idea. It might well be a more clear way to implement it once I get my head around it :) I'd rather not use frame hacks.

**Comment by d-maurer** [comment]
Dylan Jay wrote at 2019-9-8 21:24 -0700:
>...
>where I'm doing registrations dynamically using the
>local site manager instead of via ZCML.
>I don't think I can create classes on the fly here

You cannot create classes on the fly for this purpose --
but there is no need to do that: an adapter is a factory
which in many cases is a class but can be any callable, especially
a class instance.

Thus, instead of registering a class "Adapter" as adapter,
you register an instance of class "MetaAdapter".

  class Adapter:
    def __init__(self, ...): ...
    ...

  registerAdapter(Adapter, ...)

becomes

  class MetaAdapter:
    def __init__(self, name): self.name = name
    def __call__(self, ...): return Adapter(self.name, ...)

  registerAdapter(MetaAdapter(name), ...)

**Comment by djay** [comment]
@d-maurer you are a genius. Just tried it on my code and it works great!

```
class FactoryKeepingName(object):

    def __init__(self, name, factory):
        self.name = name
        self.factory = factory
    def __call__(self, *args):
        args += (self.name,)
        return self.factory(*args)
```

```
        lsm.registerAdapter(FactoryKeepingName(name, ListingView),
                           required=(IContentish, IBrowserRequest),
                           provided=IBrowserView,
                           name=name)
```
