### ISSUE TITLE
Port to GitHub Actions

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.component#52]
This won't be quite as straightforward as just running the standard configuration tool, because there are custom test environments here. Specifically, onen environment that doesn't install the 'test' extra (because it's quite large and installs many extras); instead, it installs an extra called 'mintests'. The test commands are somewhat different as well. Another environment runs with `PURE_PYTHON=1`. (They also need to run with ZOPE_INTERFACE_STRICT_IRO=1.)

I'm not sure how to do any of that with the tool (but I haven't looked).

**Comment by dataflake** [comment]
Don't forget that the tool is not an end unto itself, just a helper. What I have done in other places, such as the Zope `4.x` branch, is to simply make the changes by hand.

**Comment by jamadden** [comment]
Fixed with #56.
