### ISSUE TITLE
5.0: Remove things that were emitting a DeprecationWarning

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.component#59]

**Comment by jamadden** [comment]
There were three packages emitting deprecation warnings:

- `zope.component.interfaces` had imports from `zope.interface.interfaces`. 
- `zope.component.registry` had imports from `zope.interface.registry`
- `zope.component.hookable` was an alias for `zope.hookable`

Beyond breaking source code, we have to worry about breaking persistence. Are there any (really old) pickles in the wild that might have objects that were pickled when they lived in the old packages? 

`hookable` is easy: Nothing there should have been pickled.

It's *possible* that the other packages had some old pickles. 

Specifically, in `interfaces`, anything that `directlyProvides(obj, …)` a moved interface would be impacted. I don't think that's very likely, looking at the interfaces that moved (`IUtilityRegistration`, `IComponentRegistry`, etc). There's also `ObjectEvent`, but I think those are unlikely to be pickled (I'm guessing).

As for `registry`, that would be the concrete class `Components` and `Utility/Adapter/HandlerRegistration`. If there were persistent `Components` objects around, that should be `PersistentComponents`, which hasn't moved. The registration classes are transient and generated on demand, so they also shouldn't be pickled.

If we get complaints, and the user is unable to migrate or use an ZODB class factory to handle the redirects at runtime, we could always add back the specific import needed.

**Comment by WuShell** [comment]
Hey there!

Last week I noticed here that several of our projects were affected by the removal of these imports, mostly because those projects depend on the repoze.folder package, which imports things like the `IObjectEvent` interface, here:

https://github.com/repoze/repoze.folder/blob/master/repoze/folder/interfaces.py

I'm afraid the repoze.* packages are not maintained anymore, so I'll take a look on how to fix that.

Any hints on what could be used as a replacement of the missing `IObjectEvent` interface?

(thanks!)

**Comment by d-maurer** [comment]
Borja Lopez Rio wrote at 2021-4-5 00:10 -0700:
>Last week I noticed here that several of our projects were affected by the removal of these imports, mostly because those projects depend on the repoze.folder package, which imports things like the `IObjectEvent` interface, here:
>
>https://github.com/repoze/repoze.folder/blob/master/repoze/folder/interfaces.py
>
>I'm afraid the repoze.* packages are not maintained anymore, so I'll take a look on how to fix that.
>
>Any hints on what could be used as a replacement of the missing `IObjectEvent` interface?

Many definitions have been moved from `zope.component` to `zope.interface`.
This applies e.g. to `IObjectEvent`.

In general: many deprecation signalizations come from `deprecated` calls
which target specifically moved definitions. In this case, you can
look at the `deprecated` call (in the version were it is still available)
to find out where the definition has been moved to.

**Comment by WuShell** [comment]
Thanks @d-maurer for the reply. 

Already fixed it in repoze.folder, checked the other packages of the repoze ecosystem, found nothing to be adapted there.
