### ISSUE TITLE
Conflit between zope.component and zope.interface

### ISSUE THREAD

**Issue by tguenneguez** [zopefoundation/zope.component#66]
He,

He want to install zope.interface and zope.component.
I download whl :
zope.component-5.0.1-py2.py3-none-any.whl
zope.event-4.5.0-py2.py3-none-any.whl
zope.hookable-5.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
zope.interface-5.5.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl

When I run : 
pip3.9 install --target=/opt/application/certbot/modules --cache-dir=/images/pip_modules/ *.whl
I have got the following error : 
WARNING: Target directory /opt/application/44owas/certbot/modules/zope already exists. Specify --upgrade to force replacement.
And I have not zope.interface installed.

When I run : 
pip3.9 install --target=/opt/application/certbot/modules --cache-dir=/images/pip_modules/ *.whl --upgrade
I have no error, but I have not zope.component and event installed.

How to solve the problem

Thanks
Thomas

**Comment by mgedmin** [comment]
I wonder if this is related to `pip install --target` having trouble with old-style namespace packages.  I don't think I've ever used `pip install --target` in my life.

Have you considered creating a virtualenv and pip installing the things you need into it?

**Comment by tguenneguez** [comment]
The problem is PIP :
https://github.com/pypa/pip/issues/10629
